repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8

- repo: https://github.com/ambv/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3.9
    exclude: ^.*(response_example).*$

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
    exclude: ^.*(response_example).*$
