version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/build
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/update_source
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      runas: root