version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build/forour-backend
permissions:
  - object: /home/ubuntu/build/forour-backend
    mode: 755
    owner: root
    type:
      - directory     
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy_source
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      runas: root