version: "2.2"

services:
  web:
    build: .
    command: uvicorn app.main:server --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000

  db:
    image: postgres:12.7
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=forour
      - POSTGRES_PASSWORD=ForOur!234
      - POSTGRES_DB=forour
