name: FastAPI CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parralel: 4
      matrix:
        python-version: [ 3.8 ]
    
    steps:
    - name: Git Checkout
      uses: action/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: action/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Tests
      run: |
        pytest

